### PR TITLE
Make -colorspace argument optional

### PR DESCRIPTION
**Pull request by adamcrown**
It will still default to 'RGB' but if you explicitly pass in `save..., colorspace: nil` it will leave out the `-colorspace` option and let imagemagick figure out the best colorspace on it's own.

We've seen some problems with the `-colorspace RGB` flag causing the conversion of some PDF files to freeze, but this fixed the issue for us.

### CODE REVIEW

**Comment by jonmagic** [comment]
@adamcrown thank you for the contribution! I was wondering if you could cherry-pick db050e4433ed0f1980b8d262b080a7f490e1a6ce and 7b581ed9173a05a5b5b2c0e41be1d890f8f9cfbe into your branch? The first merges in master (I've been fixing some failing specs) and the second adds a new spec to test your changes.

**Comment by adamcrown** [comment]
@jonmagic Sure. I think this gets things where you want them. Thanks for the quick response. Just let me know if there is anything else I can do.

**Comment by jonmagic** [comment]
@adam I merged your PR, added you to the contributors list, cut version 1.3.2, and published it https://rubygems.org/gems/grim/versions/1.3.2

Thanks again!

**Comment by adamcrown** [comment]
@jonmagic Awesome! Thanks so much. I'll update my Gemfile.

**Pull request merged**
